init:
  - git config --global core.autocrlf true
services:
  - mssql2014
  - mysql
  - postgresql
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - dotnet --version
  - dotnet restore
  - msbuild
build_script:
  - dotnet build
before_test:
  - SET DOTNET_CLI_TELEMETRY_OPTOUT=1
  - SET SQLSERVER_CONNECTION_STRING=Data Source=.;Initial Catalog=tempdb;Integrated Security=True
  - SET MYSQL_CONNECTION_STRING=server=localhost;uid=root;pwd=Password12!;database=yessql;
  - SET POSTGRESQL_CONNECTION_STRING=Server=localhost;Port=5432;Database=yessql;User Id=postgres;Password=Password12!;
  - SET MYSQL_PWD=Password12!
  - PATH=C:\Program Files\MySQL\MySQL Server 5.7\bin;%PATH%
  - mysql -e "create database yessql;" --user=root'
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.4\bin\;%PATH%
  - createdb yessql
test_script:
  - dotnet test dotnet test --filter "FullyQualifiedName~YesSql.Tests.SqlServerTests" --configuration Release
clone_depth: 1
test: off
deploy: off
os: Visual Studio 2015