name: PR Check

on:

  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      POSTGRESQL_CONNECTION_STRING: Server=localhost;Port=5432;Database=yessql;User Id=root;Password=Password12!;
      MYSQL_CONNECTION_STRING: server=localhost;uid=root;pwd=Password12!;database=yessql;
      SQLSERVER_2019_CONNECTION_STRING: Server=localhost;Database=tempdb;User Id=sa;Password=Password12!;Encrypt=false;

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: Password12!
          POSTGRES_DB: yessql
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: yessql
          MYSQL_ROOT_PASSWORD: Password12!
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
        
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Password12!

    steps:
    - uses: actions/checkout@v3
    
    # as of 12/2022, 3.1 and 5.0 are not installed by default on the images
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          3.1.x
          5.0.x

    - name: Build
      run: dotnet build --configuration Release

    - name: Test - Sqlite .NET 7.0
      run: dotnet test --configuration Release --filter YesSql.Tests.SqliteTests --no-restore --no-build --framework net7.0

    - name: Test - Sqlite .NET 6.0
      run: dotnet test --configuration Release --filter YesSql.Tests.SqliteTests --no-restore --no-build --framework net6.0

    - name: Test - Sqlite .NET 5.0
      run: dotnet test --configuration Release --filter YesSql.Tests.SqliteTests --no-restore --no-build --framework net5.0

    - name: Test - Sqlite .NET 3.1
      run: dotnet test --configuration Release --filter YesSql.Tests.SqliteTests --no-restore --no-build --framework netcoreapp3.1

    - name: Test - PostgresQL .NET 7.0
      run: dotnet test --configuration Release --filter YesSql.Tests.PostgreSqlTests --no-restore --no-build --framework net7.0

    - name: Test - PostgresQL .NET 6.0
      run: dotnet test --configuration Release --filter YesSql.Tests.PostgreSqlTests --no-restore --no-build --framework net6.0

    - name: Test - MySQL .NET 7.0
      run: dotnet test --configuration Release --filter YesSql.Tests.MySqlTests --no-restore --no-build --framework net7.0

    - name: Test - MySQL .NET 6.0
      run: dotnet test --configuration Release --filter YesSql.Tests.MySqlTests --no-restore --no-build --framework net6.0

    - name: Test - SQL Server 2019 .NET 7.0
      run: dotnet test --configuration release --filter YesSql.Tests.SqlServer2019Tests --no-restore --no-build --framework net7.0

    - name: Test - SQL Server 2019 .NET 6.0
      run: dotnet test --configuration release --filter YesSql.Tests.SqlServer2019Tests --no-restore --no-build --framework net6.0

    - name: Test - PostgresQL Legacy Identity - No Schema
      run: dotnet test --configuration release --filter YesSql.Tests.PostgreSqlLegacyIdentityTests --no-restore --no-build --framework net6.0

    - name: Test - Sqlite Legacy Identity
      run: dotnet test --configuration release --filter YesSql.Tests.SqliteLegacyIdentityTests --no-restore --no-build --framework net6.0
